### ISSUE TITLE
OneXplayer Mini i7 Support (Horizontal Is Vertical, Vertical Is Horizontal)

### ISSUE THREAD

**Issue by jeongseang** [Valkirie/ControllerService#150] opened 2022-05-31 14:49 UTC
I am having an issue where the gyroscopic controls are reversed. Rotating the device horizontally will lead to vertical camera movements and rotating the device vertically will lead to horizontal camera movements. The overlay also shows this to be the case. I'm not sure if this is a software issue with Handheld Companion or a hardware issue with my OnexPlayer Mini i7-1260p.

**Comment by CasperH2O** [comment] 2022-05-31 14:51
Can you confirm, are you using the internal IMU or the USB IMU?

**Comment by jeongseang** [comment] 2022-05-31 14:52
Internal, it's the Bosch Accelerometer according to Device Manager.

**Comment by CasperH2O** [comment] 2022-05-31 14:54
Ok. Was it OK with version 0.9.8.0?

**Comment by jeongseang** [comment] 2022-05-31 14:54
I tried 0.9.8.0 and the latest version 0.9.9.0 and both of them have this issue for me.

**Comment by jeongseang** [comment] 2022-05-31 14:55
Have not tried older versions.

**Comment by CasperH2O** [comment] 2022-05-31 14:56
Please try, it will narrow down the search much quicker.

**Comment by CasperH2O** [comment] 2022-05-31 15:04
Ok. Thank you for double checking, I think I know what the problem is. Can you share a picture of the applications About page?

**Comment by jeongseang** [comment] 2022-05-31 15:07
![Screenshot (1)](https://user-images.githubusercontent.com/106607314/171206898-68e4a7aa-2a99-430a-b542-b5ed9d64be40.png)

**Comment by jeongseang** [comment] 2022-05-31 15:18
Do you think it's a software issue or could it be a case of the unit itself having implemented the accelerometer/gyroscope in a defective way?

**Comment by CasperH2O** [comment] 2022-05-31 15:20
Nope, the answer is much simpler, we don't have a configuration yet for this model's IMU mounting. You are the first!

**Comment by jeongseang** [comment] 2022-05-31 15:25
Ooh gotcha I see. Well I'd be more than happy to offer any information that could help out on this front. Appreciate the aid and prompt responses. 👍

**Comment by CasperH2O** [comment] 2022-05-31 15:29
Great, I have a test build with more logging and a simple movement test will create a logfile from which I can figure out the required changes. Will get back to you.

**Comment by jeongseang** [comment] 2022-05-31 15:31
Sounds good, thanks.

**Comment by jeongseang** [comment] 2022-05-31 21:40
[ControllerService20220531.log](https://github.com/Valkirie/ControllerService/files/8809594/ControllerService20220531.log)

Hope this worked!

**Comment by CasperH2O** [comment] 2022-06-01 05:06
Log looks decent, will investigate later in detail:

![image](https://user-images.githubusercontent.com/14330834/171331674-478ad395-30ac-4a5d-8105-e0c6588d13ba.png)

Also good news, this device is uniquely identifiable:

`2022-05-31 14:38:52.951 -07:00 [WRN] ONE XPLAYER from ONE-NETBOOK TECHNOLOGY CO., LTD. is not yet supported. The behavior of the application will be unpredictable.
`

**Comment by jeongseang** [comment] 2022-06-01 12:34
Would you happen to have a rough estimate on when the fix can be implemented and released?

**Comment by CasperH2O** [comment] 2022-06-01 12:42
From initial comparison, it seems this sensor is mounted at a 90 degree angle, which means we'd have to swap some axis instead of just inverting them. The current code for automagically detecting and changing the mounting does not support that yet, so that could be a while.

However, it shouldn't be too much work to make this change hardcoded and put an installable on the release page specifically for the OneXPlayer Mini Intel. I can have a look this evening, we might have to iterate once or twice though.

**Comment by jeongseang** [comment] 2022-06-01 13:17
Sounds good, much appreciated. Let me know if I can provide any additional information to help with iterations.

**Comment by CasperH2O** [comment] 2022-06-01 17:40
I don't recommend you tweak your sensor that way.

Please try this version: https://github.com/Valkirie/ControllerService/releases/download/bin-rc-0.9.9.0/Handheld.Companion-Release-0.9.9.0-OnexPlayer-Mini-i7-1260p.exe

If it's good, happy gaming, if not, I will prepare another debug version with extra logging.

**Comment by jeongseang** [comment] 2022-06-01 23:09
It works! I did have to invert some of the axis and that still interprets vertical as horizontal and vice versa, but with the right boxes ticked, it finally works as it should. Really appreciate it!

**Comment by Valkirie** [comment] 2022-06-22 10:26
Fixed on next build

**Closed by Valkirie** 2022-06-22 10:26 UTC
Labels: enhancement
